[package]
name = "fastsearch-mcp-bridge-temp"
version = "1.0.0"
edition = "2021"

[dependencies]
fastsearch-shared = { path = "../shared" }
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
bincode = "1.3"
thiserror = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
regex = "1.0"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.52", features = [
    "Win32_System_Pipes",
    "Win32_Foundation", 
    "Win32_System_IO",
] }
