name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_ext: .exe
          - os: ubuntu-latest  
            target: x86_64-unknown-linux-gnu
            binary_ext: ""
          - os: macos-latest
            target: x86_64-apple-darwin
            binary_ext: ""
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: ${{ matrix.target }}
        profile: minimal
        override: true
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build Rust binary
      run: cargo build --release --target ${{ matrix.target }}
    
    - name: Copy binary to bin directory
      shell: bash
      run: |
        mkdir -p bin
        cp target/${{ matrix.target }}/release/fastsearch${{ matrix.binary_ext }} bin/
    
    - name: Create npm package
      run: npm pack
    
    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          *.tgz
          bin/fastsearch${{ matrix.binary_ext }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: build-and-release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Download Windows binary
      uses: actions/download-artifact@v4
      with:
        name: fastsearch-windows-latest
        path: target/release/
    
    - name: Publish to npm
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}